# Generated by Django 2.1.4 on 2018-12-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='text',
            new_name='title',
        ),
    ]
